### ISSUE TITLE
Outdated link on 3D-e-Chem website

### ISSUE THREAD

**Issue by dominiquesydow** [3D-e-Chem/3D-e-Chem.github.io#12]
Hi!

I am getting started with the 3D-e-Chem nodes/workflows - thanks a lot for this resource!

I'd like to let you know about a minor issue, i.e. an outdated link on https://3d-e-chem.github.io/:
"Project homepage" links to https://www.esciencecenter.nl/projects/3d-e-chem, which cannot be found.

Have a good day!

**Comment by sverhoeven** [comment]
Great to hear your interest in our nodes.

Thanks for alerting me to the broken link, I fixed it.
